# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39736624376216c44505e952d9936ef322ad0c3049506886a4573afb671add286cc63f067d24ebd3742dd8d376fc0e488c0df618b144e7e6a507ffb53a23fbc5

test:
  secret_key_base: ea4036ddad6f7155403b8352890f14c0085533f0dd03f5d1d68037497d1acdf504f8f5754548603cc62378512cfc252c4bc234d8adef4e37642e07f4aec2e97e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
